<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Option Flying From</name>
   <tag></tag>
   <elementGuidId>34c76d25-443b-4f96-aeb9-ea83cccac06e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.autocomplete-results.troll.intro</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='onereturn']/div/div/div/div/div/div/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>autocomplete-results troll intro</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-highlight</name>
      <type>Main</type>
      <value>-1</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>JER JerseyJersey, JerseyJED King Abdulaziz IntlJeddah, Saudi ArabiaJEG AasiaatAasiaat, GreenlandJEE Jeremie AirportJeremie, HaitiJEJ Jeh AirportAilinglapalap Atoll, Marshall IslandsJEF Jefferson City Memorial AirportJefferson City, United StatesJES Jesup-Wayne County AirportJesup, United States</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;onereturn&quot;)/div[@class=&quot;col-md-6&quot;]/div[@class=&quot;row g-1&quot;]/div[@class=&quot;col-md-6&quot;]/div[@class=&quot;input-box input-items&quot;]/div[@class=&quot;form-group&quot;]/div[@class=&quot;autocomplete-wrapper _1 row_1&quot;]/div[@class=&quot;autocomplete-wrapper _1 row_2&quot;]/div[@class=&quot;autocomplete-results troll intro&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='onereturn']/div/div/div/div/div/div/div/div</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Flying From'])[1]/following::div[4]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Round Trip'])[1]/following::div[10]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[2]/div/div/div/div/div/div/div/div</value>
   </webElementXpaths>
</WebElementEntity>
